### ISSUE TITLE
ReferenceError: c is not defined

### ISSUE THREAD

**Issue by sam-simpleclick** [raszi/node-tmp#102]
Error ocours on windows, the below stacktrace is produced.

> ReferenceError: c is not defined
>     at _removeCallback (E:\Git\xx\Root\node_modules\tmp\lib\tmp.js:355:47)
>     at Object._cleanupCallback [as cleanup] (E:\Git\xx\Root\node_modules\tmp\lib\tmp.js:409:5)
>     ..snip..

Looks like a typo where the second reference to `_c` is `c` instead.

**Comment by sam-simpleclick** [comment]
Version: tmp@0.0.28

Will check newer version

**Comment by sam-simpleclick** [comment]
Fixed in 0.0.30. 
Should of checked first, but might help someone else with the same issue.

**Comment by raszi** [comment]
Thank you @sam-simpleclick for the verification!
