### ISSUE TITLE
Add appveyor CI and get tests passing on Windows

### ISSUE THREAD

**Issue by binki** [raszi/node-tmp#109]
When I run `npm test` on Windows for this project, I get a bunch of failures. It’d be helpful if this module could be used on Windows, but I am having some issues with cleanup not working the way I expect it to which might be a platform-specific thing—I still have to investigate. But with the starting point being a lot of test cases broken, it’d be nice to get those fixed and make sure they stay fixed with the help of CI.

I see you’re already using Travis. It seems that appveyor is quite popular among OSS projects and integrating with it is similar to Travis.

**Comment by binki** [comment]
Don’t forget to actually setup appveyor ;-).

**Comment by raszi** [comment]
Thanks @binki, it is up and running now.
