### ISSUE TITLE
Add 'contents' option

### ISSUE THREAD

**Issue by Moeriki** [raszi/node-tmp#114]
Would you be interested in an `contents` option?

Right now I'm often doing this.

```js
const tmpFile = tmp.fileSync();
fs.writeFileSync(tmpFile.name, '...');
```

**Comment by Moeriki** [comment]
Ping.

I can make pull request.

**Comment by silkentrance** [comment]
@Moeriki it is the purpose of the library to provide only a facility for creating temporary file (handlers) and temporary directories. It is not the purpose of the library to also write to these temporary files.

The recurring pattern you describe is a common pattern when using the library. Perhaps, and if you use this common pattern a lot in your code, create yourself a wrapper function that does the trick.

I'd vote against such behavior in tmp as it is not part of its defined use cases.

**Comment by Moeriki** [comment]
Wrapping is what I'm doing now :)

Ok NP. Closed.
