### ISSUE TITLE
detachDescriptor causes error with fixes for #115 in place

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#117]
The problem here is that in the removeCallback it tests for fdPath[0] being LTE 0, which is wrong, it should read -1 != fdPath[0].

This might have been found due to the side effect caused by moving the unlinkSync() back into the try block, which had been moved out of that block, causing the fix for #115 to fail.

**Comment by silkentrance** [comment]
Fixed with latest commit 02fc69f.

**Comment by raszi** [comment]
Did you want to close this issue, because that PR has not been merged yet.

**Comment by silkentrance** [comment]
Yes, I ran the tests on that branch on both appveyor and travis-ci and they work as expected.
