### ISSUE TITLE
Add ISSUE_TEMPLATE to repository

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#118]
Current reports lack viable information such as the operating system / version, the tmp version and the node js version.

I'd suggest that we add a proper template to the repository so that users can simply fill out the form.

cf. https://github.com/blog/2111-issue-and-pull-request-templates

@raszi What do you think?

### Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

### NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 

### Tmp Version
TBD:Enter tmp version here

### Expected Behavior
TBD:What have you expected tmp to do?

### Experienced Behavior
TBD:What did actually happen?

The template

```
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 

## Tmp Version
TBD:Enter tmp version here

## Expected Behavior
TBD:What have you expected tmp to do?

## Experienced Behavior
TBD:What did actually happen?
```

**Comment by raszi** [comment]
This looks good. Could you add it please? Thank you!
