### ISSUE TITLE
Fails on Windows when TEMP env var contains multiple paths

### ISSUE THREAD

**Issue by ediweissmann** [raszi/node-tmp#120]
Crazy, I know, who would add multiple paths to the `TEMP` env variable?!
Turns out this can happen: `C:\Users\Foobar\AppData\Local\Temp;C:\Program Files (x86)\Steam\`. 

Current behaviour: crashes.
Desired behaviour: detect multiple paths edge case, pick first path/any and succeed.

**Comment by raszi** [comment]
Well, this is strange. Is that really supported?

**Comment by ediweissmann** [comment]
No idea. Saw some other apps (besides ours) fail due to this.

**Comment by silkentrance** [comment]
See also https://superuser.com/questions/577022/why-would-the-temp-environment-variable-contain-more-than-one-path

@raszi I guess, and since os-tmpdir has been deprecated, that we should not try to "fix" this configuration error.

**Comment by silkentrance** [comment]
This is a configuration error at the OS level. We do not fix such things. Get your gears straight, please.
