### ISSUE TITLE
Dir is not cleaned when I hit ctrl+c

### ISSUE THREAD

**Issue by JanBednarik** [raszi/node-tmp#121]
I'm using tmp package in unit tests with `tmp.setGracefulCleanup();`. I'm creating temp directory for tests with `unsafeCleanup = true`.

It works fine if I don't hit ctrl+c to interrupt tests. Then the temp dir is not deleted. How can I get it deleted automatically in this case?

**Comment by silkentrance** [comment]
@JanBednarik Please provide additional information: OS, tmp Version, node Version etc.

Could you also give us a link to your repository, so that we may look at the code directly?

**Comment by silkentrance** [comment]
@JanBednarik ping

**Comment by silkentrance** [comment]
@JanBednarik do you work under windows?

https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js

**Comment by JanBednarik** [comment]
OS X Sierra 10.12.5

**Comment by JanBednarik** [comment]
Versions:
OS X Sierra 10.12.5
Node LTS 6.11.0
tmp 0.0.31
jest 20.0.3

Should cleanup work with ctrl+c? Maybe it's somehow related to Jest test runner. I'll try to prepare some simple failing case.

**Comment by JanBednarik** [comment]
Here is an example:

`package.json`
```
{
  "name": "tmptest",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "jest": "20.0.4",
    "tmp": "0.0.31"
  }
}
```

**Comment by JanBednarik** [comment]
Here is an example:

`package.json`
```
{
  "name": "tmptest",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "jest": "20.0.4",
    "tmp": "0.0.31"
  }
}
```

`main.test.js`
```
'use strict';

const tmp = require('tmp');

tmp.setGracefulCleanup();

test('main', done =>
    tmp.dir({ template: 'tmp-XXXXXX' }, (err, path) => {
        console.log(`dir: ${path}\npress ctrl+c`);
        setTimeout(done, 3000);
    })
);
```

Run:
```
$ npm install
$ npm test
```
And interrupt test with ctrl+c.

**Comment by silkentrance** [comment]
@JanBednarik thank your very much. I think that I have found the problem. There exists a SIGINT event and tmp should be listening on that, too. The only problem is that under Windows one must take a different approach. I will look into this.

**Comment by davidshepherd7** [comment]
This [package](https://github.com/tapjs/signal-exit) might be helpful. It's supposed to allow you to run code no matter how the process exits. It has Windows tests so presumably it works on Windows too.

**Comment by silkentrance** [comment]
@davidshepherd7 the package looks good. I will try that.

**Comment by silkentrance** [comment]
@davidshepherd7 I tried signal-exit, but to no avail so far. In addition, it also installs listeners for SIGHUP which I believe is not what we want as most user code uses this to implement some way of applying changes to the configuration etc.

https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js

**Comment by silkentrance** [comment]
@JanBednarik perhaps you want to try the gh-121 branch

If you do not know already, you can configure the tmp dependency so that it will point to that branch. See https://docs.npmjs.com/files/package.json#git-urls-as-dependencies for more information.

**Comment by silkentrance** [comment]
@JanBednarik since you are using jest, this will also fix the problem with jest's sandboxing and tmp installing its process.exit listeners multiple times.

**Comment by cythrauL** [comment]
same problem,
OSX Sierra: 10.13.1
tmp version: 0.0.33
node version: v8.9.1

**Comment by dustinjohnson13** [comment]
The provided branch `gh-121` works perfectly for me with CTRL-C for both files and directories.  Thanks!

**Comment by silkentrance** [comment]
@JanBednarik @cythrauL @davidshepherd7 the current solution, which calls upon process.exit(0) needs to be revised. Upon SIGINT the process should at least exist with a non zero (0) exit code.

**Comment by meteorlxy** [comment]
Any news on that? Hope to be fixed soon~

**Comment by Streemo** [comment]
This is also happening when using mocha, some tests are creating temp dirs, which get removed normally when the process exists naturally, but not in the CTRL+C signal. This should be as simple as adding a listener for the CTRL+C signal, and then performing the cleanup action on that signal in addition to the exit signal, right?

Should also note that `tmp.setGracefulCleanup()` was required to be called to clean up async temp dirs, even though `unsafeCleanup` was used in the options (but might be a separate issue).

**Comment by silkentrance** [comment]
@Streemo @JanBednarik The commit from the PR should fix this, it just needs to be merged down. I currently do not have the time to do that, though.

**Comment by octagonal** [comment]
@silkentrance Would it be possible to make some time to merge this? It would be very helpful for me.

**Comment by silkentrance** [comment]
@octagonal the PR failed its tests. Need to investigate.

**Comment by silkentrance** [comment]
Of course, feel free 👍

**Comment by silkentrance** [comment]
I have added one more commit to fix the tests for this issue. They seem to work, at least under OS X.

**Comment by silkentrance** [comment]
Tests work fine on travis, but fail on appveyor. It seems as if the tests do not terminate the external processes as one would expected. Fricking windows platform.

**Comment by stephanebachelier** [comment]
Any update ?

**Comment by sheerun** [comment]
We could do it ourselves if tmp exposed method like `.forceCleanup()` that removes all temporary directories created so far. Many tools like `jest` expose global teardown hooks.

**Comment by silkentrance** [comment]
The fix in branch gh-121 is working, however, the tests will not work under windows as we are having problems with simulating the CTRL-C there. And there are some conflicts that need to be resolved first prior to merging this to master. If I find the time, I can at least prepare everything so that it can be merged to master, disabling the tests on windows for now.

**Comment by silkentrance** [comment]
I am giving up on support for SIGINT on Windows. This platform just sucks as node will never 
invoke the SIGINT listener using standard kill(signal) mechanisms, which actually work just fine on POSIX based platforms such as OSX and Linux.

The current state is that it will work fine on both OSX and Linux.

**Comment by silkentrance** [comment]
On travis the tests for this still fail, locally (OSX) they will succeed, working on that issue.
