### ISSUE TITLE
Promise based API

### ISSUE THREAD

**Issue by jarrodek** [raszi/node-tmp#126]
## Operating System
All

## NodeJS Version
All except 0.10.x which doesn't support promises.

## Expected Behavior
Instead of using callback function the API always returns a Promise object for async operations.
Similar pattern to `fs-extra` can be used to not break compatibility: if callback function is not set when calling function then the function returns a promise. 

## Experienced Behavior
No promises API.

**Comment by silkentrance** [comment]
@jarrodek Please have a look at https://github.com/benjamingr/tmp-promise.

Duplicate of #74. Closing.
