### ISSUE TITLE
Switch to TS

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#131]
I noticed the switch-to-ts branch.

Will this require the typescript compiler/runtime when using the package or is this just during development?

If there are additional runtime dependencies, such as typescript, I fear that this might put people off from using the package. What do you think?

**Comment by silkentrance** [comment]
@raszi would you like to comment? or is this an experimental branch?

**Comment by raszi** [comment]
Just during the development, when deploying the package it would compile back to the selected target JS platform.

I am not sure that I want to do this, right now I am only experiencing with it. But it is already working.

**Comment by silkentrance** [comment]
Good work, just wanted to make sure that nothing else breaks.
