### ISSUE TITLE
When using the template option tmp does not join paths with opts.dir or tmpDir if no path is given in the template

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#143]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: all 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: all 

## Tmp Version
All since the time the template option was introduced up to 0.31

## Expected Behavior
When passing in the template option, tmp should join paths with either the dir option or the default tmpDir if the template does not already contain a path.

## Experienced Behavior
Temporary files and directories will be created in the CWD. In addition, both absolute and relative paths passed as part of the template will not be rejected.

## See also

#141

**Comment by silkentrance** [comment]
On second thought, we should elaborate on the template thing a bit. E.g. sprintf like functionality allowing for datetime/random chars. As it stands now, template is actually the same as a combination of the following options: dir, prefix, postfix and a random count, where count is limited to 6.

Perhaps we should also introduce a length option that allows the user to control the amount of random chars appended to the prefix.

And when using template, one should have the option to

```
"{dt:YYYYMMDD-HHMMSS}-{######}
```

and so on. What do you think of this instead of merely limiting template to a prefix/random/postfix?

**Comment by raszi** [comment]
I am not sure I like this change. First of all this is a breaking change, second this will also break the behavior of the `template` option, since it would not behave as `mkstemp` does as it is advertised in the [README](https://github.com/raszi/node-tmp/blob/master/README.md#mkstemp-like-asynchronously).

Although the idea of having a more generic templating sounds nice at the first thought but it would lead too far and I am not sure that it would be widely used. If somebody needs something like that then they could define their own and then pass the generated path as the `template`.

But I am open for further discussion about it.

**Comment by silkentrance** [comment]
@raszi Okay, I can see that backwards compatibility is an issue here.

How about then checking whether template resembles a relative or absolute path? If not, we would append opts.dir || tmpDir instead?

As for the extensions to the template: sure, this can easily be accomplished by an external templating system. How about then allowing the user to pass in a callable as a template? Which, upon invocation, would return the rendered string?

**Comment by silkentrance** [comment]
I have adjusted the description and summary.

**Comment by silkentrance** [comment]
@raszi The mkstemps like 'template system' is not compatible with the Windows platform and is very failure prone for users, especially when using hard coded paths.

See https://ci.appveyor.com/project/raszi/node-tmp/build/1.0.132/job/6cln6y1vlxxql69q

For now, I will readjust the failing test cases to use tmp.tmpdir instead and use path.join to make these test cases work.

See #141

**Comment by silkentrance** [comment]
See also #156
