### ISSUE TITLE
Moving towards 1.0.0

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#158]
As is requested by #75.

@raszi I am wanting this to finally reach 1.0.0 this year :D using the current code base. A switch over to typescript would be no problem as it would be transpiled to standard javascript and that would then be released. Or was that not your plan?

As of now, we have the unsupported legacy releases

* 0.0.33 which dropped all support for node <0.8
* 0.0.32 and below for node <0.8

and we have the 

* 0.1.0 release branch which still supports node 0.10.0+

The 0.1.0 we can use for maintenance work in case that major problems arise. The existing issues including the still open issues #129, #155, and #121 should also make it into this release. But we would not integrate new features into that "branch", if any such new features arise in the future.

See also the compatibility notice in the readme on current master.

And from 1.0.0 on I would like to drop support for all node versions < 4.0.0, so we can have #108.

And given 1.0.0 we could be moving to typescript and a gulp based build process, see #157.

What do you think? Sounds like a good plan to me.

**Comment by silkentrance** [comment]
for reference #75 #108

**Comment by poppinlp** [comment]
Hi.
How this play going? According to [this report](https://nodesource.com/node-by-numbers) i think it's a good idea to drop support for node versions < 4.x. So is there any contribution needed? :)

**Comment by raszi** [comment]
According to [this document](https://github.com/nodejs/Release#nodejs-release-working-group) we can drop the support as soon as  04/30/2018.

**Comment by wtgtybhertgeghgtwtg** [comment]
4/30/2018 has passed.  Are you going to drop `os-tmpdir`?

**Comment by raszi** [comment]
Yes, we should.

**Comment by silkentrance** [comment]
os-tmpdir has long been dropped 😄

**Comment by Krinkle** [comment]
@silkentrance Yeah, I'm master. The last release, however, appears to have been in 2017.

**Comment by markstos** [comment]
That's right. I just installed `tmp` from NPM and the dependency on `os-tmpdir` is still there.

**Comment by jarrodek** [comment]
So,
According to NodeJS docs currently versions >= 10 are the only supported versions (today it is 10, 12, and 13). So I guess support for any older version can be safely dropped as organizations are moving towards upgrading libraries to work on supported by Node platforms.

I would suggest to move the API towards Promise based APIs. Everyone now are using async functions and suddenly using callbacks is just inconvenient. I would be happy to work on the PR if the is the direction the library will move forward as I am using it in multiple projects.

**Comment by alubbe** [comment]
Just to add to the above point, the `tmp-promise` project would be interested in merging their promisified code to this project, if there's interest. @raszi would you be interested in a PR in that direction?
https://github.com/benjamingr/tmp-promise/issues/36
