### ISSUE TITLE
v0.1.0 not published in npm

### ISSUE THREAD

**Issue by jmendiara** [raszi/node-tmp#160]
npm reports the last published version as 0.0.33

https://www.npmjs.com/package/tmp

That was intended?

**Comment by silkentrance** [comment]
@jmendiara yes, 0.0.33 was the last version published on npm. At the moment we are working on 0.1.0, which is in master and which might get published soon after that #121 and #155 have been fixed.
After that, I would like to drop support for node < 4.0.0 completely and release a 1.0.0, see #108 and #75.

**Comment by jmendiara** [comment]
oh! ok, ok. sorry. I think you bumped package.json version and forgot to publish. 👍

**Comment by silkentrance** [comment]
@jmendiara thanks. but you do not need to be sorry nor worry :grin:
