### ISSUE TITLE
Where is the Promisified API?

### ISSUE THREAD

**Issue by Jakobud** [raszi/node-tmp#167]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [X] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [X] 7.x
- other: 

## Tmp Version
Latest

In your documentation you say 
> There also exists a promisified version of the API, see (5) under references below.

I see nothing in the documentation or the API pages about Promise usage or the API methods returning a thenable().

**Comment by silkentrance** [comment]
Please see the README.md for more information: https://github.com/raszi/node-tmp

There is a link to it in the document.

**Comment by Jakobud** [comment]
Wow that is really weird. I could have sworn that tmp-promise link was not there before. Maybe my eyes are going bad. Thanks

**Comment by silkentrance** [comment]
@Jakobud it might be missing in the official API docs 😀 and here also https://www.npmjs.com/package/tmp

**Comment by Jakobud** [comment]
Oh that's it. The published Readme on npmjs.com must be old. Thanks
