### ISSUE TITLE
Should `_rmdirRecursiveSync` be re-implemented using a loop?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [raszi/node-tmp#17]
See [#840(bower)](https://github.com/bower/bower/issues/840).

When there are a large number of directories to clean up, the current implementation seems to result in a "Maximum call stack size exceeded" exception.

**Comment by silkentrance** [comment]
Way too complicated, just use an array as a stack and fill this up with the directories that need to be cleaned, emptying the stack along the way and everything is fine...

Will provide a PR for this.
