### ISSUE TITLE
get RAM temp dir /dev/shm

### ISSUE THREAD

**Issue by roccomuso** [raszi/node-tmp#173]
Wouldn't be also useful to have a way to get a tmp dir in RAM?

like `/dev/shm` in linux

**Comment by silkentrance** [comment]
@roccomuso This is up to you and how your system has been configured. AFAIK this cannot be implemented in node-tmp as it will require setting up a memory based tmpfs.

**Comment by raszi** [comment]
You can achieve the requested functionality by passing the `dir` option and setting that to `/dev/shm` on Linux:

```javascript
tmp.file({ dir: '/dev/shm' }, (err, name, fd, fnn) => {});
```
