### ISSUE TITLE
I need more control over appveyor builds, please

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#185]
@raszi 

With #121 I need to have more control over the appveyor jobs as they are constantly hitting a timeout (1hr per build), with 5 builds per commit this is not acceptable :grin:.

While I could be fixing things on my windows machine, I would rather have it to work in the CI environment.

Please see https://help.appveyor.com/discussions/problems/6493-user-permissions-button-to-cancel-build-not-visible for more information.

**Comment by silkentrance** [comment]
@raszi having to wait for appveyor builds to fail is a PITA, please give me some control over the build jobs, so that I can stop/restart them as needed.

**Comment by raszi** [comment]
After a short struggle with AppVeyor I believe I succeeded. Could you please check whether you have the right permissions?

**Comment by silkentrance** [comment]
Thank you very much. Works like a charm :+1:
