### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by strugee** [raszi/node-tmp#191]
This project could use a change log. In particular 0.1.0 has just been released and it's exceedingly difficult to determine what has actually changed in this version compared with the previous release.

See also https://keepachangelog.com. Thanks for maintaining this project!

**Comment by whollacsek** [comment]
I'm also going through this trying to figure out what changed since 2016. In addition to the change log can we also promote this package to v1.0.0 and get regular minor releases?

Maybe using a tool like https://github.com/zeit/release

**Comment by eight04** [comment]
Does anyone have a summary about what has been changed for v0.1.0?

**Comment by silkentrance** [comment]
I am currently working on incorporating a changelog. ATM this will be hand crafted, since we do not have any commits that would support a standardized way for collecting changelog information in an automated fashion.

**Comment by silkentrance** [comment]
> Does anyone have a summary about what has been changed for v0.1.0?

no.

**Comment by raszi** [comment]
In my comment https://github.com/raszi/node-tmp/pull/234/files#r377256378 I recommended to the https://github.com/ekata/github-changelog project and I believe all the PRs are formatted correctly for that, so we can generate the changelog anytime.

**Comment by silkentrance** [comment]
@raszi I reckon that, thanks for the link btw. however, I needed to make this as fast as possible, and doing it by hand and not fiddling around with errs on behalf of github-changelog, I decided otherwise. And I think I tried the solution but it then gave me no suitable results?
I will give it another try soon.

**Comment by silkentrance** [comment]
We are actively using lerna-changelog over at `testdeck`, however, this requires that all pull requests are labelled with `bug`, `enhancement`, ... and so on.

**Comment by silkentrance** [comment]
Will look into this, closing for now.

**Comment by silkentrance** [comment]
I have found the time for looking into this.

## github-changelog

- uses commit messages for classifying the nature of the commit
- in the past we did not care about any conventions when creating these messages, so the overall output is quite messy and the result is not beautiful

```
 * @satazor: Uncaught exception (#8)
 * @aeosynth: use os.tmpDir (#7)
 * @joscha: Bumped version (#6)
 * @joscha: Export _getTmpName for temporary file name creation (#5)
 * @joscha: Please export _getTmpName (#4)
 * @node-migrator-bot: Hi! I fixed some code for you! (#3)
 * @fat: In 0.8.0 path.exists became fs.exists :) (#2)
 * @chilts: Fix the default tmp dir (fixes a few tests) (#1)
```

## lerna-changelog

- creates beautiful results and we are also able to change the past by labelling our past pull requests

```
## v0.2.0 (2020-04-25)

#### :bug: Bug Fix
* [#193](https://github.com/raszi/node-tmp/pull/193) Closes [#192](https://github.com/raszi/node-tmp/issues/192): tmp must not exit the process on its own ([@silkentrance](https://github.com/silkentrance))

#### Committers: 2
- Carsten Klein ([@silkentrance](https://github.com/silkentrance))
- Mattias Severson ([@matsev](https://github.com/matsev))


## v0.1.0 (2019-03-20)

#### :rocket: Enhancement
* [#141](https://github.com/raszi/node-tmp/pull/141) test: refactor tests for mocha ([@silkentrance](https://github.com/silkentrance))

#### Committers: 6
- Anna Henningsen ([@addaleax](https://github.com/addaleax))
- Carsten Klein ([@silkentrance](https://github.com/silkentrance))
- Dan Kerimdzhanov ([@kerimdzhanov](https://github.com/kerimdzhanov))
- Gustav Klingstedt ([@gutte](https://github.com/gutte))
- KARASZI István ([@raszi](https://github.com/raszi))
- PoppinL ([@poppinlp](https://github.com/poppinlp))
cklein@bilbo:~/workspaces/01-coldrye/01-collaboration/node-tmp/node-tmp$ ./node_modules/.bin/lerna-changelog --from v0.0.1

## v0.2.0 (2020-04-25)

#### :rocket: Enhancement
* [#221](https://github.com/raszi/node-tmp/pull/221) Gh 206 document name option ([@silkentrance](https://github.com/silkentrance))

#### :bug: Bug Fix
* [#193](https://github.com/raszi/node-tmp/pull/193) Closes [#192](https://github.com/raszi/node-tmp/issues/192): tmp must not exit the process on its own ([@silkentrance](https://github.com/silkentrance))

#### Committers: 2
- Carsten Klein ([@silkentrance](https://github.com/silkentrance))
- Mattias Severson ([@matsev](https://github.com/matsev))


## v0.1.0 (2019-03-20)

#### :rocket: Enhancement
* [#141](https://github.com/raszi/node-tmp/pull/141) test: refactor tests for mocha ([@silkentrance](https://github.com/silkentrance))

#### :memo: Documentation
* [#180](https://github.com/raszi/node-tmp/pull/180) fix gh-179: template no longer accepts arbitrary paths ([@silkentrance](https://github.com/silkentrance))
* [#175](https://github.com/raszi/node-tmp/pull/175) docs: add `unsafeCleanup` option to jsdoc ([@kerimdzhanov](https://github.com/kerimdzhanov))

#### Committers: 6
- Anna Henningsen ([@addaleax](https://github.com/addaleax))
- Carsten Klein ([@silkentrance](https://github.com/silkentrance))
- Dan Kerimdzhanov ([@kerimdzhanov](https://github.com/kerimdzhanov))
- Gustav Klingstedt ([@gutte](https://github.com/gutte))
- KARASZI István ([@raszi](https://github.com/raszi))
- PoppinL ([@poppinlp](https://github.com/poppinlp))
```

**Comment by silkentrance** [comment]
@raszi personally I would go for lerna-changelog as it produces the best results

**Comment by silkentrance** [comment]
@raszi I invested the time and labelled all merged PRs and here is the result from lerna-changelog

https://gist.github.com/silkentrance/430fd1725279750e5f3f0470de7d120f

This definitely looks great. It misses releases < v0.0.14, though.

Still, awesome result for just 10 minutes time.

**Comment by raszi** [comment]
Looks good!

**Comment by silkentrance** [comment]
Great, I was just preparing a PR for this.

**Comment by silkentrance** [comment]
PR #253

**Comment by bmerigan** [comment]
The outdated changelog file combined with no release notes is making it very difficult to know of any breaking changes.
