### ISSUE TITLE
removeCallback() is not actually synchronous

### ISSUE THREAD

**Issue by dieseldjango** [raszi/node-tmp#197]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [x] MacOS
- other:

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 10.16.0

## Tmp Version
0.1.0

## Expected Behavior

```
const tmp = require('tmp');
const fs = require('fs');

const tmpobj = tmp.fileSync();
console.log(`Created ${tmpobj.name}`);
tmpobj.removeCallback();
console.log(`Still exists: ${fs.existsSync(tmpobj.name)}`);
setImmediate(() => { console.log(`Still exists after setImmediate: ${fs.existsSync(tmpobj.name)}`); });
```

`removeCallback()` is described as synchronous. Running the code above, I would expect both console.log statements checking for the removed file to return `false`.

## Experienced Behavior

`removeCallback()` isn't really synchronous, it is just an asynchronous operation that doesn't provide a promise or callback. Is this the intended behavior?

**Comment by silkentrance** [comment]
Internally, the operation should be synchronous. However, and as it seems, the overall behaviour of thd node fs api was changed. We will need to investigate this.

**Comment by silkentrance** [comment]
This was fixed in #198 I believe.

**Comment by silkentrance** [comment]
However, I will look into the callback once again.

**Comment by silkentrance** [comment]
You are right. The callback returned is async. Let's see how we can fix this.

**Comment by silkentrance** [comment]
This might boil down to #198, still.

**Comment by silkentrance** [comment]
@dieseldjango you might want to try with latest master, which has the fix for #198 in place.

**Comment by silkentrance** [comment]
No, it was not fixed with #198:

```
  const removeCallback = _prepareRemoveCallback(_removeFileAsync, [fd, name], removeCallbackSync);
```

as it will use the async API for removing the file.

**Comment by silkentrance** [comment]
Perhaps we can even get rid of some code here, if we make this sync instead of async and sync on cleanup.

**Comment by silkentrance** [comment]
I think that with the two available interfaces, one sync and the other async, the two should return sync and async callbacks, respectively.
