### ISSUE TITLE
setGracefulCleanup() doesn't ALWAYS clean up file.

### ISSUE THREAD

**Issue by brillout** [raszi/node-tmp#199]
## Expected Behavior

When using `setGracefulCleanup()` the file should not exist anymore after the process is terminated.

## Experienced Behavior

`setGracefulCleanup()` works when the process receives a SIGINT but doesn't when the signal is SIGTERM or SIGKILL.

Same if the the machine were to unexpectedly crash, e.g. the machine's power is shut down.

On linux, the trick would be to create a file and to delete it right away while still having the file open. (As mentioned [here](https://stackoverflow.com/a/687023/270274).)

## Env

- OS: Linux
- NodeJS: v12.2.0
- `tmp@0.1.0`

**Comment by silkentrance** [comment]
@brillout It seems as if 12.2.0 introduced even more changes under the hood.

**Comment by silkentrance** [comment]
@brillout This seems to be what we are experiencing in #198.
I already made a fix for that in https://github.com/raszi/node-tmp/tree/matsev-update-dependencies-to-latest-versions.

**Comment by silkentrance** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by silkentrance** [comment]
Fixed with #198.
