### ISSUE TITLE
How to create a tmp file with extension

### ISSUE THREAD

**Issue by ktalebian** [raszi/node-tmp#200]
How can I create a tmp file with an extension?

**Comment by bartvanandel** [comment]
There is an option called `postfix`. E.g., this will create a file named `prefix-???-postfix.txt` where `???` is some random string inserted by the library:
```js
const txtFileObj = tmp.fileSync({
    prefix: `prefix-`,
    postfix: '-postfix.txt',
});
```

**Comment by silkentrance** [comment]
Thanks to @bartvanandel for answering the question.

See also the options https://github.com/raszi/node-tmp#options
