### ISSUE TITLE
removeCallback() does not do anything

### ISSUE THREAD

**Issue by yanickrochon** [raszi/node-tmp#203]
## Operating System
- [X] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 12.10.0

## Tmp Version
- 0.1.0

## Expected Behavior
When I call a remove function, I expect it to remove something, or throw otherwise

## Experienced Behavior
Nothing happens.

**Comment by silkentrance** [comment]
This seems to be related to #202.

**Comment by silkentrance** [comment]
Fixed with #198.
