### ISSUE TITLE
Custom graceful shutdown is broken

### ISSUE THREAD

**Issue by mikalai-ramashka** [raszi/node-tmp#208]
## Operating System
- [ x] Linux
- [ x] Windows 7
- [ x] Windows 10
- [ x] MacOS
- other: 

## NodeJS Version
- [x] 0.x
- [x] 4.x
- [x] 6.x
- [x] 7.x
- other:  12

## Tmp Version
0.1

## Expected Behavior
do not call process.exit(0);

## Experienced Behavior
We have previously implemented graceful shutdown for our own goals (save data, close files, stop servers), but `tmp` just call process.exit(0) and stop correct exiting flow.

**Comment by silkentrance** [comment]
Duplicate of #193
