### ISSUE TITLE
create withTmpName that automatically cleans up after callback

### ISSUE THREAD

**Issue by NodeGuy** [raszi/node-tmp#22]
I would like to have another version of `tmpName` that automatically cleans up the temporary file (if created) after the callback completes.  It would prevent temporary files from building up during long running processes and could look something like this:

```JavaScript
function withTmpName(options, callback) {
  var
    args = _parseArguments(options, callback),
    opts = args[0],
    cb = args[1];

  return _getTmpName(opts, function (error, name) {
    try {
      cb(error, name);
    }
    finally {
      child_process.execFile('rm', ['--recursive', '--force', name]);
    }
  });
}
```

I was going to create a pull request but couldn't figure out how to test this properly using Vows.

**Comment by silkentrance** [comment]
#25 works just fine with #38 in place. Considering this a NOFIX.
