### ISSUE TITLE
Remove template option

### ISSUE THREAD

**Issue by silkentrance** [raszi/node-tmp#239]
The template option in its current form is a useless and utterly redundant feature and must be eliminated with no further warning as to its deprecation.

One can always use the standard prefix/postfix/dir option to achieve a similar result, with the random part being 12 instead of 6 chars.

We could also add a name length option that will allow the user to specify name lengths in the range of 6..18 characters.

**Comment by raszi** [comment]
The template feature was added because tmp was based on [`mkstemp`](https://en.wikipedia.org/wiki/Mkstemp).

It might seem redundant but before sunsetting it I believe we should do some analysis of its usage.

**Comment by silkentrance** [comment]
@raszi how would you make such a usage analysis? integrate google analytics? 😬  - the most part of the users of tmp do not actually care unless we break the API.
