### ISSUE TITLE
Octal literals are not allowed in strict mode.

### ISSUE THREAD

**Issue by JackMiszencin** [raszi/node-tmp#24]
I'm using tmp in a karma test file, and the inclusion of 'use strict;' at the top of the file is causing me to get this error:
`Uncaught SyntaxError: Octal literals are not allowed in strict mode.`

The backtrace sends me to the line where I create the tempfile:

`tmp.file({ mode: 0644, prefix: 'prefix-', postfix: '.pdf' }, function _tempFileCreated(err, path, fd) {`

Does tmp use octal literals? If so, can I avoid them somehow?

**Comment by ibc** [comment]
Isn't much easier to just use `0x644` syntax?
