### ISSUE TITLE
tmpNameSync: Bad result if the TMP/TEMP env. variables are enclosed in quotes

### ISSUE THREAD

**Issue by haneefdm** [raszi/node-tmp#246]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ x] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 10.16.2

## Tmp Version
TBD:0.1.0

## Expected Behavior
TBD: What have you expected tmp to do?

Create proper tmp-name without quotes

## Experienced Behavior
TBD: What did actually happen?

Created path names with embedded quotes if the env. vars TMP and TEMP has spaces in it. I have a space in my user name and we have to use our own TMP directories rather than using the system ones. To reproduce the problem in a shell/cmd set the TMP/TEMP variables to any path with spaces in it

  set TMP="C:\users\xxx\T M P"
  set TEMP="C:\users\xxx\T M P"
  node test.js

The above commands creates the following output. Yes, I can filter the path-name but it was unexpected
```
Created temporary filename:  "C:\Users\hdm\T M P"\tmp-4832vNUYEwQFRehF
```

And my test.js looks like
```JavaScript
var tmp = require('tmp');
var options = {};
var tmpname = tmp.tmpNameSync(options);
console.log('Created temporary filename: ', tmpname);
```

**Comment by silkentrance** [comment]
This also applies to the dir option and the template option.

**Comment by silkentrance** [comment]
The downside of this is that the user may no longer include a single single quote or a single double quote in the path.

**Comment by haneefdm** [comment]
Please, please don't make any changes; I was wrong. Quotes are part of the string I suppose.

I am so so sorry to report this issue and wasted your time.

**Comment by silkentrance** [comment]
Way too late :smile:. This has already been merged and I think that it is ok handling this rather fringe case. The user might also be passing in a string for template or name or dir that might contain single quotes or double quotes.
