### ISSUE TITLE
Why SIGINT rather than beforeExit?

### ISSUE THREAD

**Issue by arcanis** [raszi/node-tmp#247]
I'm using `tmp` in Yarn, but it causes problems where other SIGINT handlers aren't registered due to `tmp` overriding them with its own (I'm not entirely sure about the order of execution to be honest, but it's clear `tmp` has a role into this).

Why is `node-tmp` catching SIGINT in the first place rather than using the `beforeExit` handler?

**Comment by lpgera** [comment]
Yeah, this issue caused a massive headache for me too. Our production web app relies on a `SIGINT` handler to shut down (or reload) gracefully, which it started to not do after we've included this package.

**Comment by CleyFaye** [comment]
In addition, why is the SIGINT handler done the way it is now?
From my understanding, it is fine to register multiple handlers on the same signal. The way it is now it makes sure that any handler registered after tmp is included is not called.

Isn't it better to leave this kind of signal management alone? Right now it break regular usage of the signal.

**Comment by raszi** [comment]
Closed by #233
