### ISSUE TITLE
Provide functions to retrieve existing files created by tmp

### ISSUE THREAD

**Issue by robross0606** [raszi/node-tmp#249]
tmp exposes mechanisms to create files, and has internal functions to look for existing files.  However, those functions to look at existing files are not exposed.  Why not expose some of those to have a more complete CRUD library?

**Comment by silkentrance** [comment]
@robross0606 but you do have every means of getting the files. You will be handed out the absolute path to the file or directory. And from there you can use standard fs module provided methods for dealing with the database which is the filesystem.

Tmp's internals are meant for automatic garbage collection on process exit.
