### ISSUE TITLE
removeCallback() fails after updating to 0.2.0

### ISSUE THREAD

**Issue by BryanHunt** [raszi/node-tmp#251]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [x ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 12.16.2

## Tmp Version
0.2.0

## Expected Behavior
Clean up the tmp directory

## Experienced Behavior
Error: ENOTEMPTY: directory not empty, rmdir '/var/folders/0p/35rj_jpx365f0plgs12ydxw40000gn/T/tmp-56630-mXjXpcliphmp'

If I revert to 0.1.0, the problem goes away.

**Comment by silkentrance** [comment]
@BryanHunt you need to configure the temporary directory with unsafeCleanup = true or call tmp.setUnsafeCleanup().

If you keep files in the temporary directory, then these will not be removed automatically, when removing the directory.

**Comment by silkentrance** [comment]
@BryanHunt I need your feedback here. Did adding the unsafeCleanup option solve your problem?

**Comment by BryanHunt** [comment]
I need a day or so to try it out.  I've been swamped with other work issues.

**Comment by silkentrance** [comment]
@BryanHunt okay. take your time.

**Comment by okcompute** [comment]
I'm seeing similar behaviour on my end. Read-only files/folders cannot be automatically removed with version 0.2.0. This was working fine with 0.10. Could it be a regression introduced by the package now using RimRaf?

**Comment by BryanHunt** [comment]
I was able to get unsafeCleanup = true working :)

**Comment by silkentrance** [comment]
@okcompute while this is not directly related to the issue, can you provide e.g. a gist with the steps you are taking that lead to the described behaviour? how come these files/directories become read only?

**Comment by silkentrance** [comment]
@okcompute you mean 0.1.0? this is already using rimraf.

**Comment by okcompute** [comment]
@silkentrance Yes, I realized after the fact my comment should have been posted in a new issue :). We use `node-tmp` in our test suite for creating temporary fixtures. In some cases, we are testing our system behaviour with read-only files. So we create a temporary directory. Create a random file in the temp folder. Set the read-only flag on that file. Run our test. And finally, call `node-tmp` clean-up callback. With `0.1.0`, this works perfectly. With `0.2.0`, the clean up callback fails. 

> @okcompute you mean 0.1.0? this is already using rimraf.

Ok. My bad, I saw that RimRaf was added in my `package-lock.json`. I thought this was coming from `node-tmp` version update.

**Comment by silkentrance** [comment]
@okcompute have you tried creating the temporary directory with the option `{unsafeCleanup: true}`?
Otherwise rimraf will not be used and tmp is expected to fail on non empty directories.

**Comment by okcompute** [comment]
Yes, this is how I'm calling the function:

`  const tempDir = tmp.dirSync({ unsafeCleanup: true })`

**Comment by silkentrance** [comment]
@okcompute after which you somehow create the files (using tmp.fileSync()?) and then set the readonly status, what is with the fd returned by tmp, do you detach it or discard it? if you detach it, you need to make sure that you close the file.

**Comment by silkentrance** [comment]
@okcompute please provide a gist of an example of the actual steps taken, including also the measures taken to create the temporary files. (pseudo code is ok.)

**Comment by okcompute** [comment]
Then I create a file in that folder (not using `tmp`). Manually set the read-only flag to the file. Run my test. Manually call `tmp` cleanup function. I don't touch the `fd` returned by `tmp`.

**Comment by okcompute** [comment]
> @okcompute please provide a gist of an example of the actual steps taken

Will do.

**Comment by silkentrance** [comment]
@okcompute thanks, this will help a lot.

**Comment by silkentrance** [comment]
Considering this resolved. Having readonly files and directories inside the temporary directory created by tmp has not been on our radar yet and is an entirely different issue.

@okcompute feel free to open a new issue.
