### ISSUE TITLE
Prefix and postfix - redundant dashes

### ISSUE THREAD

**Issue by justanotheranonymoususer** [raszi/node-tmp#256]
## Tmp Version
0.2.1

## Expected Behavior
When I use the following example code from the readme:
```
tmp.file({ mode: 0o644, prefix: 'prefix-', postfix: '.txt' }, /*...*/);
```
I expect to get a filename like this:
`prefix-blabla-blabla.txt`
That was the behavior in old versions.

## Experienced Behavior
I get a filename like this:
prefix--blabla-blabla-.txt

While the first redundant dash can be fixed by removing `-` from `prefix`, the dash before the extension stays there. 
i.e. If I have `postfix: '.txt'`, I get `[...]bla[...]-.tmp`.

**Comment by silkentrance** [comment]
@justanotheranonymoususer nice find. Never thought of the suffix actually being meant for an file name extension. But since it is documented that way, we need to fix that.

My proposal would be to test for a leading dot `.`. If it is there, the hyphen `-` will be omitted. If it is not, then a hyphen will be included in the so generated file name.

What do you think?

**Comment by justanotheranonymoususer** [comment]
Works for me. But it's a special case, so how about the following more
general solution:

Only add a dash after prefix if it ends with one of [a-zA-Z0-9].
Only add a dash before suffix if it begins with one of [a-zA-Z0-9].

This way, the example will be still valid, and the dash won't have to be
removed from prefix as well.

**Comment by silkentrance** [comment]
@justanotheranonymoususer would you care to provide us with a PR?

**Comment by silkentrance** [comment]
@justanotheranonymoususer I did not forget your issue. However, I am having a hard time with this, as the suffix is always meant to be a part of the filename and not representing its extension, e.g. `.txt`.

Apart from that, tmp is not meant to write out the terminal file. As of its nature, tmp will just write out temporary files. And if you need them to have a specific extension, feel free to use the available fs methods to move/rename an existing tmp file to a location where it gets persisted.

Closing as invalid.

**Comment by silkentrance** [comment]
TODO fix the documentation.

**Comment by silkentrance** [comment]
@justanotheranonymoususer and since you are the only person who reported this, I think that we are safe with limiting the prefix.
