### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by guimard** [raszi/node-tmp#259]
## Operating System
- [X] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 12.x

## Tmp Version
TBD: 0.2.1

## Expected Behavior
TBD: I'd like to have 0.2.1 tag in GitHub to be able to rebuild tmp from source

## Experienced Behavior
TBD: GitHub tags end with 0.2.0 while npm registry published 0.2.1

**Comment by raszi** [comment]
Sorry, fixed.
