### ISSUE TITLE
method to get current base dir path

### ISSUE THREAD

**Issue by stefanocudini** [raszi/node-tmp#263]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 

## Tmp Version
TBD:Enter tmp version here

## Expected Behavior
TBD:What have you expected tmp to do?

## Experienced Behavior
TBD:What did actually happen?

**Comment by silkentrance** [comment]
@stefanocudini please state your intent.. there is `tmp.tmpdir` for the standard tmpdir path.

**Comment by stefanocudini** [comment]
exactly!
