### ISSUE TITLE
Unknown "devtmpnodejsnpm-cache" folder

### ISSUE THREAD

**Issue by Avivhdr** [raszi/node-tmp#269]
## Operating System
- [ ] Windows 10

## NodeJS Version
- [ ] 15.7.0

## IDE
- [ ] VSCode

## Experienced Behavior

Though I'm not using this module directly, every time I'm installing any new module in any of my projects using `npm install`, a folder with the name of "devtmpnodejsnpm-cache" is being created in the root folder of that particular project.
See image:
![image](https://user-images.githubusercontent.com/23265867/120890890-dd028c80-c605-11eb-91a4-2d5459bbffe0.png)

Searching this folder name in google brings **0** results:
![image](https://user-images.githubusercontent.com/23265867/120890955-39fe4280-c606-11eb-9751-98d90f4f396e.png)

Does this folder has anything to do with node-tmp?
If not, do you know what is it?

**Comment by silkentrance** [comment]
npmjs does not use the tmp module.

See https://docs.npmjs.com/cli/v7/commands/npm-cache for more information about the npm caching system.

Maybe also have a look at your npm configuration, it might override the default location, which should be 

```
Default: Windows: %LocalAppData%\npm-cache
Posix: ~/.npm
```

**Comment by Avivhdr** [comment]
Great.
Thanks!

My `.npmrc` file had `cache=C:userdevtmpnodejsnpm-cache`
And I changed it to: `cache=C:\Users\Aviv\AppData\Local\npm-cache`
