### ISSUE TITLE
Why does tmp.setGracefulCleanup() not work within jest tests?

### ISSUE THREAD

**Issue by rzacherl** [raszi/node-tmp#273]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [x] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 14.15.0

## Tmp Version
0.2.1

## Expected Behavior
Files created inside a jest test via tmp.fileSync() should get deleted automatically after the test ends (as it happens within the normal code)

## Experienced Behavior
Files are still existing after jest test finished

**Comment by silkentrance** [comment]
@rzacherl It has been a while... Sorry, my bad.

In the past, jest would use sandboxes and not necessarily terminate the process. So tmp cleanup will not run until all tests have been run and the jest process exits.

If you need to have these files removed early, then you need to call the `removeCallback` at the end of your test.

**Comment by silkentrance** [comment]
Graceful cleanup only happens on process exit and not in-between test cases.

You need to manually call the remove callback in order to remove these files in-between tests.
