### ISSUE TITLE
0.2.2 was tagged but not published

### ISSUE THREAD

**Issue by mbargiel** [raszi/node-tmp#284]
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 

## Tmp Version
N/A

## Expected Behavior
Expected npmjs registry to have 0.2.2 as the latest release.

## Experienced Behavior
0.2.2 was tagged (August 2022), but 0.2.1 is still the latest release on the npmjs registry. (Note that the `package.json` version was not changed to 0.2.2 before tagging, so you may need to move the tag or sacrifice 0.2.2 and go to 0.2.3).

Note: I saw the PR #281 to rewrite the whole library in TypeScript. I would strongly suggest that you first publish the fix that I contributed via #278 (basically the only code change in "v0.2.1...v0.2.2", I think) before doing this since not every JavaScript project is configured to work with TypeScript. Thanks!

**Comment by silkentrance** [comment]
@mbargiel thanks for the information. I don't know why it was tagged and the version field was not bumped to the actual version.

As for the typescript based rewrite: it will be transpiled to plain javascript so that every dependent can use it.

**Comment by silkentrance** [comment]
I think that we can safely delete the tag.

**Comment by mbargiel** [comment]
Awesome, thanks for reassuring me 😁 You can close this Issue at your leisure then (unless you want to keep it as a reminder for making a release before the rewrite, since I saw there were some discussions and points to settle in that PR...? Anyway, your call!)

**Comment by silkentrance** [comment]
I have removed the invalid v0.2.2 tag since no release nor a deployed version on npm depended on it.

**Comment by silkentrance** [comment]
No problem. However, I am not able to publish a new version to npmjs.com.

**Comment by liviubunda** [comment]
It does look like version 0.2.2 appears in the documentation and changelog, but can't be found on npm.

@silkentrance What do you mean when you say you are not able to publish a new version to npm?

**Comment by stianjensen** [comment]
Does another maintainer have the permission to push it to npm?

**Comment by raszi** [comment]
I missed this somehow. I am pushing to the npm repositories and I did not publish nor tag `v0.2.2`.

I can do the following days.
