### ISSUE TITLE
npm test generates a bunch of uncleaned tmp files

### ISSUE THREAD

**Issue by shime** [raszi/node-tmp#31]

**Comment by silkentrance** [comment]
This also relates to #36

**Comment by silkentrance** [comment]
@raszi You might want to have a look at this...

Still unresolved are using-name tests and some of the spawn tests that IMO fail to clean up after themselves.

**Comment by silkentrance** [comment]
It seems as if the error is in the removeCallback. It tries to closeSync the fd first. Failing that, it will not unlink the file.

Will prepare a PR for this.

**Comment by silkentrance** [comment]
@raszi With the latest patches this should no longer be an issue, don't you think?
