### ISSUE TITLE
Tmp files left open after clean up

### ISSUE THREAD

**Issue by mtomy** [raszi/node-tmp#33]
Hello!

I wrote small test:

``` javascript
exports.test = function(req, res) {
    tmp.file(function(err, path, fd, cleanupCb) {
        if (!err) {
            console.log("tmp file: " + path);
            cleanupCb();
        } else
            console.error(err); 
        res.send(200);
    });
}
```

After several HTTP requests I run `lsof | grep `pgrep node`` and see this:

node      11001       root   14u      REG      252,0        0    1048588 /tmp/tmp-11001edg7x80.tmp (deleted)
node      11001       root   15u      REG      252,0        0    1048589 /tmp/tmp-11001op2r768.tmp (deleted)
node      11001       root   16u      REG      252,0        0    1048590 /tmp/tmp-110013qclg7k.tmp (deleted)
node      11001       root   17u      REG      252,0        0    1048591 /tmp/tmp-110011t9lx5c.tmp (deleted)
node      11001       root   18u      REG      252,0        0    1048592 /tmp/tmp-11001lrluw8g.tmp (deleted)
node      11001       root   19u      REG      252,0        0    1048593 /tmp/tmp-110015f9wkow.tmp (deleted)
node      11001       root   20u      REG      252,0        0    1048594 /tmp/tmp-11001sswb6gg.tmp (deleted)
node      11001       root   21u      REG      252,0        0    1048595 /tmp/tmp-11001irf0scg.tmp (deleted)
node      11001       root   22u      REG      252,0        0    1048596 /tmp/tmp-11001lqrm9zk.tmp (deleted)
node      11001       root   23u      REG      252,0        0    1048597 /tmp/tmp-11001n0bgvfk.tmp (deleted)

All temp files deleted, but open by node process. It looks like bug, but probably it is behavior expected.

PS If I additionally call fs.close(fd) everything is ok.

Thank you.

**Comment by mtomy** [comment]
Thanks for reply!

After calling cleanupCb client does not need file to stay open. So I think API could be simplified by closing file inside cleanupCb. 

It is also a good practice to close file at the same layer where it was open. At this moment file opened inside node-tmp module, but must be closed at client code.

Probably I don't see bigger picture :)

**Comment by jb55** [comment]
Yeah I was just bitten by this in production. cleanup should close the file descriptor...

**Comment by jb55** [comment]
Ignore that, looks like it does and it was a different issue I was having...
