### ISSUE TITLE
_rmdirRecursiveSync Race condition on windows

### ISSUE THREAD

**Issue by heri16** [raszi/node-tmp#35]
_rmdirRecursiveSync causes a race condition in windows (nodejs domains) that causes:

   { message: 'ENOTEMPTY, directory not empty \'C:\\Users\\ec2-user\\AppData\\Local\\Temp\\2\\tmp-2068nvmg128\'',
     stack: 'Error: ENOTEMPTY, directory not empty \'C:\\Users\\ec2-user\\AppData\\Local\\Temp\\2\\tmp-2068nvmg128\'\n
  at Object.fs.rmdirSync (fs.js:624:18)\n    at _rmdirRecursiveSync (C:\\Users\\ec2-user\\cps-mailin\\node_modules\\tmp\
\lib\\tmp.js:201:6)\n    at C:\\Users\\ec2-user\\cps-mailin\\node_modules\\tmp\\lib\\tmp.js:218:5\n    at C:\\Users\\ec2
-user\\cps-mailin\\lib\\cps-rene.js:155:24\n    at Object.cmdTypes.AdjustXmlImport (C:\\Users\\ec2-user\\cps-mailin\\lib
\\cps-rene.js:17:1)\n    at C:\\Users\\ec2-user\\cps-mailin\\lib\\cps-rene.js:154:28\n    at C:\\Users\\ec2-user\\cps-ma
ilin\\node_modules\\async\\lib\\async.js:254:17\n    at done (C:\\Users\\ec2-user\\cps-mailin\\node_modules\\async\\lib\
\async.js:135:19)\n    at C:\\Users\\ec2-user\\cps-mailin\\node_modules\\async\\lib\\async.js:32:16\n    at C:\\Users\\e
c2-user\\cps-mailin\\node_modules\\async\\lib\\async.js:251:21' } }

**Comment by silkentrance** [comment]
It seems as if some of the files have not been deleted inside the temporary folder. Could you provide more specific information as to the files being created and whether there are other processes that have locks on these files while attempting to remove them?

**Comment by silkentrance** [comment]
This might have been resolved for the PR for #17, #42 (good number :grin:)

**Comment by silkentrance** [comment]
@heri16 please try again with the latest version of node-tmp and report your issues here.

**Comment by raszi** [comment]
This has been fixed with your PR #42, I am closing this now.

@heri16 if you could reproduce this, please don't hesitate to reopen the issue. Thank you!
