### ISSUE TITLE
_garbageCollector leaks if keep is false

### ISSUE THREAD

**Issue by bmeck** [raszi/node-tmp#48]
_removeObjects never gets cleaned up if you call a cleanup function. it only ever gets appended to, this causes leaks for long lived processes that create many temporary file/dirs. when cleanup functions are called they should remove their temp file from _removedObjects.

the workaround right now is to always set `keep:true` and assume you are doing cleanup yourself

**Comment by bmeck** [comment]
@raszi ^

**Comment by chrisbartley** [comment]
This should be reopened.  It still leaks when `keep:false`.  

Here's an example which demonstrates the leak.  First, add an else clause to `_prepareRemoveCallback` which prints out the size of the `_removeObjects` array, and add some logging to the if clause:

```javascript
function _prepareRemoveCallback(removeFunction, arg) {
  var called = false;

  return function _cleanupCallback() {
    if (called) return;

    var index = _removeObjects.indexOf(removeFunction);
    if (index >= 0) {
      console.log("removing from _removeObjects");
      _removeObjects.splice(index, 1);
    } else {
      console.log("_removeObjects.length = [" + _removeObjects.length + "]");
    }

    called = true;
    removeFunction(arg);
  };
}
```

Then run the following:

```javascript
var tmp = require('tmp');
var fs = require('fs');

var createTempFile = function() {
   tmp.file({ prefix : 'tmp_memory_leak_test_', postfix : '.txt', keep : false },
         function(err, tempFilePath, tempFileDescriptor, tempFileCleanupCallback) {
            if (err) {
               console.log("Error trying to create the temp file.  Will attempt cleanup.");
               tempFileCleanupCallback();
            }
            else {
               fs.writeFile(tempFilePath,
                            "Hello world, the current time is: " + Date.now() + "\n",
                            function(err) {
                               if (err) {
                                  console.log("Error trying to write the file.  Will attempt cleanup.");
                                  tempFileCleanupCallback();
                               }
                               else {
                                  tempFileCleanupCallback();
                                  setTimeout(createTempFile, 1);
                               }
                            });
            }
         });
};

createTempFile();
```

You'll see that `removing from _removeObjects` is never printed (because `_removeObjects.indexOf(removeFunction)` always returns -1) and that `_removeObjects.length` increases indefinitely.

**Comment by silkentrance** [comment]
@chrisbartley bummer, but, it is rather late right now, I will have a look at this tomorrow evening :smile:

**Comment by silkentrance** [comment]
@chrisbartley having run some tests in the REPL with the extracted _prepareRemoveCallback function yields no errors, the _removeObjects array gets cleaned up properly. Will try again tomorrow evening with a proper test case.
