### ISSUE TITLE
Differences with node-temp library in README out-of-date

### ISSUE THREAD

**Issue by bruce** [raszi/node-tmp#54]
Regarding the safety of the `node-temp` library; it has used `O_CREAT | O_TRUNC | O_RDWR | O_EXCL` since 2012 (bruce/node-temp#7). I'd appreciate an update to your README when you have an opportunity. :beers:

**Comment by raszi** [comment]
Yes, thanks for noticing!

It wasn't using that back then when that README was written [more than a year before](4c7ec607debf0bb32f4d50f87090b8d995eede38) that security feature was merged into node-temp.
