### ISSUE TITLE
cleanup should accept a callback for composition

### ISSUE THREAD

**Issue by bmeck** [raszi/node-tmp#57]
right now cleanup is a synchronous function which cannot wrap a callback, this means you need to wrap any node convention callbacks like so:

```
// fs.writeFile...
function onFileWrite(err) {
  cleanup();
  return cb.apply(this, arguments);
}
```

or just a simple way to avoid having this liter code.

**Comment by silkentrance** [comment]
@bmeck please be more specific, to which cleanup() function do you refer to? There is none in the tmp API...

**Comment by silkentrance** [comment]
@raszi is this in any way related to node-tmp?

**Comment by bmeck** [comment]
@silkentrance I am referring to https://github.com/raszi/node-tmp/blob/216a2bf4544498ec42a43e718bee3e7b173ccb0a/lib/tmp.js#L387-L397 ,

right now any tool like `aysnc` off npm has to wrap the cleanup callback like above it if is a step in a series:

```javascript
tmp.dir(function _tempDirCreated(err, path, cleanupCallback) {
// work with tmp file

// cleanup
async.series([
  ...
  function cleanupTmpFile(next) {
    cleanupCallback();
    next(null);
  },
  ...
], ...)
})
```

vs:

```javascript
tmp.dir(function _tempDirCreated(err, path, cleanupCallback) {
// work with tmp file

// cleanup
async.series([
  ...
  cleanupCallback,
  ...
], ...)
})
```

this convention of calling another function is pretty prevalent in various APIs for node, but is not there for node-tmp

**Comment by silkentrance** [comment]
@bmeck Well, this makes it rather clear, thank you for the detailed information. The fix is rather simple and I am sure that you can provide @raszi with a PR for this as well.

**Comment by silkentrance** [comment]
@bmeck @raszi reviewing this while gaining more insight knowledge, I thins that node-tmp must/should (@raszi?) not make any assumptions on the frameworks being used. as such it should be agnostic to such framework induced idioms such as calling a ``next`` callable.

**Comment by silkentrance** [comment]
@bmeck how about a PR or did the synchronous API solve your problems?
