### ISSUE TITLE
ENOENT error in Appveyor NodeJS v0.10.39

### ISSUE THREAD

**Issue by jviotti** [raszi/node-tmp#58]
I'm getting the following issue, only on `v0.10.39` under Windows in a module that uses `tmp` in a test suite:

```sh
> resin-image-manager@3.0.0 prepublish C:\projects\resin-image-manager
> gulp build
 
[15:47:40] Requiring external module coffee-script/register
[15:47:40] Using gulpfile C:\projects\resin-image-manager\gulpfile.coffee
[15:47:40] Starting 'lint'...
[15:47:41] Starting 'test'...
[15:47:41] Starting 'coffee'...
[2J[1;3H[15:47:42] 'test' errored after 1.22 s
[15:47:42] Error in plugin 'gulp-mocha'
Message:
    ENOENT, open 'C:\Users\appveyor\AppData\Local\Temp\1\tmp-2156tKPc2tEDYtRU.tmp'
Details:
    errno: 34
    code: ENOENT
    path: C:\Users\appveyor\AppData\Local\Temp\1\tmp-2156tKPc2tEDYtRU.tmp
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: ENOENT, open 'C:\Users\appveyor\AppData\Local\Temp\1\tmp-2156tKPc2tEDYtRU.tmp'
 
 
 
  22 passing (360ms)
 
[15:47:42] Finished 'coffee' after 1.51 s
[15:47:42] Finished 'lint' after 1.56 s
 
npm ERR! resin-image-manager@3.0.0 prepublish: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resin-image-manager@3.0.0 prepublish script.
npm ERR! This is most likely a problem with the resin-image-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls resin-image-manager
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\projects\resin-image-manager
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
Command exited with code 1
```

Notice that the test suite passes (22 passing (360ms)), however the ENOENT error prevents `npm` to consider it a success.

The error is being thrown in Appveyor CI (http://www.appveyor.com), however I've been unable to reproduce in a Windows 8 PC with the exact same NodeJS version.

The build works on Appveyor in version `0.11` and `0.12`. 

Luckily, Appveyor build histories seem to be publicly available, so you can more closely inspect the logs here: https://ci.appveyor.com/project/jviotti/resin-image-manager.

If you want to try to reproduce, run the test suite of the following module: https://github.com/resin-io/resin-image-manager.

The error message doesn't say much, so not sure if I should be asking the Appveyor support team instead.

**Comment by jviotti** [comment]
I've been able to reproduce the issue with NodeJS `v0.10.39` in Windows 7.

**Comment by jviotti** [comment]
Using `fs.unlink()` instead of the provided remove callback fixed the issue: https://github.com/resin-io/resin-image-manager/pull/3/files. Might be worth to investigate in more depth why the provided remove callback doesn't work as expected.

**Comment by silkentrance** [comment]
Could you please provide a full stack trace?

**Comment by silkentrance** [comment]
@jviotti this might be due to the fact that the first test case does not write anything to the file and node taking a shortcut here and never creating the file in the first place, but I am just guessing.

OTOH fs.unlink() will never fail, even on non existing paths.

**Comment by silkentrance** [comment]
@raszi I believe that in the removeCallback we need a try/catch around 

https://github.com/raszi/node-tmp/blob/master/lib/tmp.js#L345

the fs.closeSync() checking for ENOENT and failing if ENOENT was not the actual cause.

What do you think, could this be the cause of this? I mean, without having a full stack trace this is just guessing...

**Comment by jviotti** [comment]
@silkentrance I'll revisit this issue and provide more details tomorrow.

**Comment by jviotti** [comment]
@silkentrance I cannot reproduce anymore in the same Windows PC :/. I'll re-open in case the issue re-appears.
