### ISSUE TITLE
On Mac 10.9 with node 0.10.40, throws an error cannot find module rimraf

### ISSUE THREAD

**Issue by manimis902** [raszi/node-tmp#59]
The rimraf js is present in the node_modules/rimraf/ , in the same folder as temp.js and at the global scale too. Still, the module loading is failing.

Doesn't seem to happen on ubuntu 12.04 with node 0.10.38

**Comment by raszi** [comment]
`tmp` does not depend on `rimraf`, the `temp` module depends on `rimraf` but it is a different project, please open the issue [there](https://github.com/bruce/node-temp/issues).

**Comment by manimis902** [comment]
My Bad. Thanks for redirecting me to correct repo.
