### ISSUE TITLE
Cleaning up tmp directory throws an error

### ISSUE THREAD

**Issue by rubenvereecken** [raszi/node-tmp#82]
The error is

```
Error: ENOTEMPTY: directory not empty, rmdir '/tmp/tmp-96377PyPfMXvxq0t'
```

and it's pretty obvious what it's complaining about. I wrote to the temporary directory and now it doesn't want to clean it up because something is inside. In `rm` terms, I should use `-f`.

The problem I have with this is that there's probably always something inside this temporary directory. Shouldn't the library clean this up regardless?

**Comment by raszi** [comment]
I am not sure. If you create temporary directories and you create files in them which should be cleaned up after your program exits then you should create those files as temp files as well.

**Comment by rubenvereecken** [comment]
Ah didn't know I could have temp files within a certain directory. I could have a look at that.

**Comment by rosskevin** [comment]
@raszi I have the same problem.  I create a `tmp.dirSync()` and pass the `name` downstream as a base path with for other plugins to write tmp files in that directory.  At the end of my gulp, I just want to cleanup anything there, which would effectively mean `rm -Rf`.  I can work around it but I agree with @rubenvereecken that this is expected behavior.

**Comment by rubenvereecken** [comment]
I'm glad I'm not the only one. Could we change the current implementation
to match the semantics those of us who use it expect? There's no one
actually hoping for an error while there are still files in the temp
directory which they are trying to clean.

**Comment by raszi** [comment]
Well, did you try the `unsafeCleanup` option?

**Comment by nicolas-raoul** [comment]
Stupid question: How to use the options?
`tmp.dirSync("unsafeCleanup");` does not work.

**Comment by raszi** [comment]
```javascript
tmp.dirSync({ unsafeCleanup: true});
```
