### ISSUE TITLE
proposed enhancement: nofd option

### ISSUE THREAD

**Issue by pabigot** [raszi/node-tmp#88]
Would you be interested in a patch that adds an option `nofd` which, if present, avoids opening a file descriptor corresponding to the created temporary file?  The corresponding `fd` parameter in the callback would then be undefined.

The use case I have in mind is where the name will be used in an API like `fs.createReadStream()` where the pre-opened descriptor consumes system resources for no value. Looking at the tmp.js code I don't believe I can just `fs.close(fd)` and continue to use the name, because at the point `cleanupCallback()` is invoked the original `fd` will be closed even if it's no longer associated with the temporary file.

**Comment by silkentrance** [comment]
See also https://github.com/raszi/node-tmp/issues/91#issuecomment-252511232.

**Comment by pabigot** [comment]
I've attempted to explain why the problem is not a race condition [here](https://github.com/raszi/node-tmp/issues/91#issuecomment-252514448).

In any case I have no idea what synchronous operations have to do with this proposal, nor why `tmp` needs to hold the descriptor.  AFAICT the only thing ever done with it is to close it when the remove callback is invoked.
