### ISSUE TITLE
Please publish 0.0.29

### ISSUE THREAD

**Issue by algesten** [raszi/node-tmp#89]
We got hit by a crash in production today. 

```
> /usr/local/delivery-service/.tmp/nar-delivery-service-v2.8.1-bin-1473056064807/node_modules/tmp/lib/tmp.js:355
>       if (e.errno != -_c.EBADF && e.errno != -c.ENOENT) {
>                                               ^
> 
> ReferenceError: c is not defined
```

The fix for it was done in 058fe4cba624af1e1aff07cdda67442e4e1f940a however there hasn't been a release since it was fixed. I understand you don't want to do a 1.0.0 (#75), but perhaps you could release a 0.0.29 with the current code?

**Comment by raszi** [comment]
Sorry for the delay.
