### ISSUE TITLE
removeCallback can close descriptor belonging to another file system operation

### ISSUE THREAD

**Issue by pabigot** [raszi/node-tmp#91]
This bug motivated the enhancement proposed in issue #88, which I've now taken the time to confirm.

Because the removeCallback() captures the descriptor opened when the tmpFile was created, any operation that closes that descriptor while not removing the tmpFile releases the descriptor for use in other operations.  When the original tmpFile is removed the descriptor is closed even though it now belongs to another activity.

This behavior makes the fd parameter extremely dangerous to use.

The example program below demonstrates the problem.

```
'use strict';

const tmp = require('tmp');
const fs = require('fs');

tmp.file((err, name1, fd1, removeCallback1) => {
  console.log(`file1 ${name1} descriptor ${fd1}`);
  fs.close(fd1, err => {
    console.log(`closed ${fd1}`);
    tmp.file((err, name2, fd2, removeCallback2) => {
      console.log(`file2 ${name2} descriptor ${fd2}`);
      fs.fstat(fd2, (err, stat) => {
        if (err) {
          return console.log('fd2 bad to begin', err);
        }
        console.log('fd2 is valid');
        removeCallback1();
        console.log('removed tmp1');
        fs.fstat(fd2, (err, stat) => {
          if (err) {
            return console.log('fd2 is broken', err);
          }
          console.log('fd2 ok', stat);
        });
      });
    });
  });
})
```

Output on my system:

```
file1 /tmp/tmp-32363NIXdmdAsP1uJ.tmp descriptor 9
closed 9
file2 /tmp/tmp-3236365hcFJMjvC6c.tmp descriptor 9
fd2 is valid
removed tmp1
fd2 is broken { [Error: EBADF: bad file descriptor, fstat] errno: -9, code: 'EBADF', syscall: 'fstat' }
```

**Comment by silkentrance** [comment]
@pabigot since the system reuses fd descriptor ids once they have been freed you need to call removeCallback1() outside the callback for tmp.file(...fd2).

**Comment by pabigot** [comment]
@silkentrance I think you've missed the point.  I'm using `tmp` to create a unique file name which I will use in multiple operations, possibly over an arbitrarily long period.  I don't want the file removed because it has content that I'm going to need later, which I can still access because I know its name.  The descriptor is an artifact of the way the uniqueness was guaranteed; I don't want to leave it open for the life of the file because the limit on concurrently open descriptors is far smaller than the number of files that can be put on a file system.

**Comment by silkentrance** [comment]
@pabigot yes, as mentioned before, I do understand your usecase. 

the reason i call this a race condition is that you must make sure that the order by which you remove the files, and with that also close the file descriptors is important when claoing the fds yourself.

I.e.

open tmp1
  close fd1 manually
   open tmp2
     close fd2 manually
     call remove callback 2
  call remove callback 1


so callng remove callback 2 must come first, otherwise you run into the rac condition.

**Comment by pabigot** [comment]
@silkentrance If it happened that I was able to record the order of operations, I might be able to unwind them.  But the simplified reproducing code I provided does not fully represent the behavior of the application, where the two (or more) temporary files are used in independent asynchronous activities and their open/close/use path/remove operations may be interleaved (which is what I meant by the use case).

At any rate pull request #94 provides the solution I need, and as an orthogonal enhancement should not affect existing uses.  My hope is that @raszi will be open to it.

**Comment by jnj16180340** [comment]
Somewhat related, common file operations release the temporary file's fd which makes its cleanup fail. For example (linux, node 6.9.1)
````javascript
    async.waterfall([
        function(callback) {
            var tmpobj = tmp.fileSync({prefix:'',postfix:'-'+srcKey});
            s3.getObject({Bucket:srcBucket,Key:srcKey})
                .createReadStream()
                .pipe(fs.createWriteStream(null,{fd:tmpobj.fd}))
                .on('finish',function(){
                    callback(null, tmpobj);
                })
                .on('close',function(){console.log('FD CLOSED!!');});
        },
        function(tmpobj, callback) {
            console.log('Path is: '+tmpobj.name);
            console.log('FD is: '+tmpobj.fd);
            fs.fstat(tmpobj.fd, (err,stat) => { console.log(err ? 'no access!' : stat);});
            callback(null, tmpobj);
        },
        function(tmpobj,callback) {
            console.log('cleaning up');
            setTimeout(function(){tmpobj.removeCallback();},2000)
            callback(null, 'done cleaning up');
        }
    ], function (err, result) {
        console.log('Waterfall done');
    });
````
produces  
````
Path is: /tmp/tmp-790hb6pbCWcnJu8-joyrex-mfm.jpg
FD is: 15
cleaning up
Waterfall done
FD CLOSED!!
no access!
Error: EBADF: bad file descriptor, close
    at Error (native)
    at Object.fs.closeSync (fs.js:609:18)
    at _removeCallback (/usr/src/app/nodejs/node_modules/tmp/lib/tmp.js:348:10)
    at Object._cleanupCallback [as removeCallback] (/usr/src/app/nodejs/node_modules/tmp/lib/tmp.js:408:5)
    at Timeout._onTimeout (repl:37:30)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
````
It looks like EBADF should be caught by cleanup callback, but `require('constants').EBADF` is `undefined` on node 6.9.1. Explicitly replacing `-_c.EBADF` with `-9` fixes the above error and the temp file seems to get cleaned up. In node 4, `require('constants').EBADF` is correctly defined.

**Comment by silkentrance** [comment]
@jnj16180340 Very good find. In node 7.x the constants have been removed entirely. Furthermore, constants is considered internal and should not have been used in the first place.

See http://stackoverflow.com/a/14392235/4646986. As of at least node 7.x, error.code is equal to the name of the error, e.g. EBADF or ENOENT.

Don't know how this works out on windows, though.

**Comment by jnj16180340** [comment]
@silkentrance done, see #95... pushed a super quick fix that still uses internal constants. I assume referring to error names ENOENT etc. on windows is okay (see https://msdn.microsoft.com/en-us/library/5814770t.aspx ) but can't test it right now
